layout:
  qmk_info_json: ./flactyl_layout.json
  qmk_layout: default
layers:
  config:
    - bootloader
    - t: reset
      h: keyboard
    - t: $$mdi:bluetooth$$
      h: BLE clear
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:bluetooth$$
      h: BLE 1
    - t: $$mdi:bluetooth$$
      h: BLE 2
    - t: $$mdi:bluetooth$$
      h: BLE 3
    - t: $$mdi:bluetooth$$
      h: BLE 4
    - t: $$mdi:bluetooth$$
      h: BLE 5
    - t: $$mdi:bluetooth$$
      h: BLE prev
    - t: $$mdi:bluetooth$$
      h: BLE next
    - t: $$mdi:bluetooth$$
      h: select BLE
    - t: $$mdi:cancel$$
    - t: $$mdi:usb$$
      h: select USB
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: reset
      h: keyboard
    - bootloader
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
    - t: $$mdi:cancel$$
combos: []
