layout:
  qmk_info_json: ./flactyl_layout.json
  qmk_layout: default
layers:
  default:
    - t: Q
      h: CMD-SLASH
      s: ALT-CMD-Q
    - t: W
      h: CMD-W
      s: CMD-Q
    - t: F
      h: CMD-F
      s: ALT-CMD-F
    - t: P
      h: CMD-P
      s: SFT-CMD-P
    - t: '&none'
      h: '&tog config'
    - t: A
      h: CMD-A
    - t: R
      h: CMD-R
    - t: S
      h: CMD-S
    - t: T
      h: CMD-T
    - t: G
      h: CMD-G
      s: CMD-SFT-G
    - Z
    - X
    - C
    - t: D
      h: CMD-D
    - t: B
      h: CMD-B
      s: CMD-SFT-B
    - h: windows
      t: $$tabler:box-multiple$$
    - h: arrows
      t: $$tabler:box-multiple$$
    - h: numbers
      t: $$tabler:box-multiple$$
    - t: $$tabler:hand-move$$
      h: scroll
    - t: $$tabler:mouse$$
      h: click l
    - t: $$tabler:mouse$$
      h: click r
    - t: '&none'
      h: '&tog config'
    - t: L
      h: CMD-L
    - t: U
      h: CMD-U
    - t: 'Y'
      h: CMD-Y
    - t: '1'
      h: '2'
      s: '3'
    - t: M
      h: CMD-M
    - t: 'N'
      h: CMD-N
      s: CMD-SFT-N
    - t: E
      h: CMD-E
      s: SFT-CMD-E
    - t: I
      h: CMD-I
      s: CMD-ALT-I
    - t: O
      h: CMD-O
    - t: J
      h: CMD-J
    - t: H
      h: CMD-H
    - t: V
      h: CMD-V
    - t: K
      h: CMD-K
    - t: $$tabler:mouse$$
      h: click l
    - t: $$tabler:space$$
    - h: symbols
      t: $$tabler:box-multiple$$
    - t: $$mdi:apple-keyboard-shift$$
    - ''
    - ''
    - ''
combos:
  - p:
      - 8
      - 13
    k:
      t: paste
      h: pasteMulti
  - p:
      - 7
      - 12
    k: copy
  - p:
      - 6
      - 11
    k: cut
  - p:
      - 38
      - 37
    k: deleteWord
  - p:
      - 4
      - 21
    k: '&tog qwerty'
  - p:
      - 16
      - 17
    k:
      t: $$mdi:apple-keyboard-control$$
  - p:
      - 16
      - 15
    k:
      h: windows2
      t: $$tabler:box-multiple$$
